// <auto-generated />
using System;
using BioTrack.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioTrack.Server.Migrations
{
    [DbContext(typeof(BioDataContext))]
    [Migration("20260213070723_AddProtocolDeviation")]
    partial class AddProtocolDeviation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BioTrack.Server.Models.AdverseEvents", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("EventID");

                    b.HasIndex("ParticipantID");

                    b.ToTable("AdverseEvents");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ComplianceReports", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<decimal>("AdherenceRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DeviationCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("ProtocolID");

                    b.ToTable("ComplianceReports");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ConsentForm", b =>
                {
                    b.Property<int>("ConsentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsentID"));

                    b.Property<string>("FileUri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("ConsentID");

                    b.HasIndex("ParticipantID");

                    b.ToTable("ConsentForms");
                });

            modelBuilder.Entity("BioTrack.Server.Models.Observations", b =>
                {
                    b.Property<int>("ObservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservationID"));

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("BodyTemperature")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Creatinine")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<int>("Hemoglobin")
                        .HasColumnType("int");

                    b.Property<decimal>("OxygenSaturation")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<int?>("ProtocolID")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ObservationID");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("ProtocolID");

                    b.ToTable("Observations");
                });

            modelBuilder.Entity("BioTrack.Server.Models.Participants", b =>
                {
                    b.Property<int>("ParticipantID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BloodPressure")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("int");

                    b.Property<int?>("SiteID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("Temperature")
                        .HasColumnType("float");

                    b.HasKey("ParticipantID");

                    b.HasIndex("ProtocolID");

                    b.HasIndex("SiteID");

                    b.ToTable("Participants", (string)null);
                });

            modelBuilder.Entity("BioTrack.Server.Models.ProtocolDeviation", b =>
                {
                    b.Property<int>("DeviationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviationId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ObservationID")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipantsParticipantID")
                        .HasColumnType("int");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReportedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("DeviationId");

                    b.HasIndex("ObservationID");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("ParticipantsParticipantID");

                    b.HasIndex("ProtocolID");

                    b.HasIndex("ReportedDate");

                    b.HasIndex("Severity");

                    b.ToTable("ProtocolDeviations", (string)null);
                });

            modelBuilder.Entity("BioTrack.Server.Models.ResearcherCredentials", b =>
                {
                    b.Property<int>("ResearcherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResearcherId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResearcherId");

                    b.ToTable("ResearcherCredentials");
                });

            modelBuilder.Entity("BioTrack.Server.Models.StudySites", b =>
                {
                    b.Property<int>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiteID"));

                    b.Property<string>("InvestigatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrincipalInvestigatorId")
                        .HasColumnType("int");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("int");

                    b.HasKey("SiteID");

                    b.HasIndex("PrincipalInvestigatorId");

                    b.HasIndex("ProtocolID");

                    b.ToTable("StudySites", (string)null);
                });

            modelBuilder.Entity("BioTrack.Server.Models.TrialProtocols", b =>
                {
                    b.Property<int>("ProtocolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProtocolID"));

                    b.Property<decimal>("CompletionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EnrollmentRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProtocolID");

                    b.ToTable("TrialsProtocols", (string)null);
                });

            modelBuilder.Entity("BioTrack.Server.Models.TrialReports", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProtocolID")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.HasIndex("ProtocolID");

                    b.ToTable("TrialsReports");
                });

            modelBuilder.Entity("StudySiteResearchers", b =>
                {
                    b.Property<int>("SiteID")
                        .HasColumnType("int");

                    b.Property<int>("ResearcherId")
                        .HasColumnType("int");

                    b.HasKey("SiteID", "ResearcherId");

                    b.HasIndex("ResearcherId");

                    b.ToTable("StudySiteResearchers", (string)null);
                });

            modelBuilder.Entity("BioTrack.Server.Models.AdverseEvents", b =>
                {
                    b.HasOne("BioTrack.Server.Models.Participants", "Participant")
                        .WithMany("AdverseEvents")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ComplianceReports", b =>
                {
                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "TrialProtocol")
                        .WithMany("ComplianceReports")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrialProtocol");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ConsentForm", b =>
                {
                    b.HasOne("BioTrack.Server.Models.Participants", "Participant")
                        .WithMany("Consents")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("BioTrack.Server.Models.Observations", b =>
                {
                    b.HasOne("BioTrack.Server.Models.Participants", "Participant")
                        .WithMany("Observations")
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "Protocol")
                        .WithMany()
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Participant");

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("BioTrack.Server.Models.Participants", b =>
                {
                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "TrialProtocol")
                        .WithMany("Participants")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioTrack.Server.Models.StudySites", "StudySite")
                        .WithMany("Participants")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StudySite");

                    b.Navigation("TrialProtocol");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ProtocolDeviation", b =>
                {
                    b.HasOne("BioTrack.Server.Models.Observations", "Observation")
                        .WithMany()
                        .HasForeignKey("ObservationID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BioTrack.Server.Models.Participants", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BioTrack.Server.Models.Participants", null)
                        .WithMany("ProtocolDeviations")
                        .HasForeignKey("ParticipantsParticipantID");

                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "TrialProtocol")
                        .WithMany()
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Observation");

                    b.Navigation("Participant");

                    b.Navigation("TrialProtocol");
                });

            modelBuilder.Entity("BioTrack.Server.Models.StudySites", b =>
                {
                    b.HasOne("BioTrack.Server.Models.ResearcherCredentials", "PrincipalInvestigator")
                        .WithMany("PrincipalInvestigatorSites")
                        .HasForeignKey("PrincipalInvestigatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "TrialProtocol")
                        .WithMany("StudySites")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrincipalInvestigator");

                    b.Navigation("TrialProtocol");
                });

            modelBuilder.Entity("BioTrack.Server.Models.TrialReports", b =>
                {
                    b.HasOne("BioTrack.Server.Models.TrialProtocols", "TrialProtocol")
                        .WithMany("TrialReports")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrialProtocol");
                });

            modelBuilder.Entity("StudySiteResearchers", b =>
                {
                    b.HasOne("BioTrack.Server.Models.ResearcherCredentials", null)
                        .WithMany()
                        .HasForeignKey("ResearcherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudySiteResearchers_ResearcherCredentials_ResearcherId");

                    b.HasOne("BioTrack.Server.Models.StudySites", null)
                        .WithMany()
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StudySiteResearchers_StudySites_SiteID");
                });

            modelBuilder.Entity("BioTrack.Server.Models.Participants", b =>
                {
                    b.Navigation("AdverseEvents");

                    b.Navigation("Consents");

                    b.Navigation("Observations");

                    b.Navigation("ProtocolDeviations");
                });

            modelBuilder.Entity("BioTrack.Server.Models.ResearcherCredentials", b =>
                {
                    b.Navigation("PrincipalInvestigatorSites");
                });

            modelBuilder.Entity("BioTrack.Server.Models.StudySites", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("BioTrack.Server.Models.TrialProtocols", b =>
                {
                    b.Navigation("ComplianceReports");

                    b.Navigation("Participants");

                    b.Navigation("StudySites");

                    b.Navigation("TrialReports");
                });
#pragma warning restore 612, 618
        }
    }
}
